In [2]:
import numpy as np
print("Kindly enter the entries of your 4*4 matrix in one go. Like the first row, enter from left to right. Then in the next row, enter from left to right and so on.")
entries = list(map(int, input().split()))

Kindly enter the entries of your 4*4 matrix in one go. Like the first row, enter from left to right. Then in the next row, enter from left to right and so on.
1 2 3 4


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2],[4,1,2,3]])

N=4

def transpose(A,B):
    for i in range(N):
        for j in range(N):
            B[i][j]=A[i][j]

A=arr
B=np.zeros((4,4))
transpose(A,B)

print("Transpose of matrix is: ")
print(B)

reshape_B=B.reshape((2,8))

print(reshape_B)




Transpose of matrix is: 
[[1. 2. 3. 4.]
 [2. 3. 4. 1.]
 [3. 4. 1. 2.]
 [4. 1. 2. 3.]]
[[1. 2. 3. 4. 2. 3. 4. 1.]
 [3. 4. 1. 2. 4. 1. 2. 3.]]


In [ ]:
arr=np.array(entries).reshape(4,4)
arrt=arr.T
arr2_8=arrt.reshape(2,8)

In [ ]:
#Printing with box brackets
print(arrt)
print('\n')
print(arr2_8)
print('\n')
#printing without box brackets with the help of 2 for loops.
for i in range(0,4):
  for j in range(0,4):
    print(arrt[i,j],end=' ')
  print('\n')  
for i in range(0,2):
  for j in range(0,8):
    print(arr2_8[i,j],end=' ')
  print('\n')      

[[1 5 9 3]
 [2 6 0 4]
 [3 7 1 5]
 [4 8 2 6]]


[[1 5 9 3 2 6 0 4]
 [3 7 1 5 4 8 2 6]]


1 5 9 3 

2 6 0 4 

3 7 1 5 

4 8 2 6 

1 5 9 3 2 6 0 4 

3 7 1 5 4 8 2 6 

